abukhadraop-or/reverifi-api

src/controllers/listing.js
src/migrations/20220105090607-modify-listings.js
src/models/listing.js
src/routes/listings.js
src/services/listing.js

<Ticket>
Create route to handle listings pagination 
http://reverifi-api.docker/api/listings/feature/:page 
Get 3 listings per page for home page listings feature

Listings home feature

---

docker-compose.yml
src/controllers/listing.js
src/migrations/20220117095308-modify-listings-agentId-ownerId.js
src/models/listing.js
src/models/user-info.js
src/routes/users.js
src/swagger.yml

listings-user-auth-endpoints
1- Create new migration to change (allow null) for agent_id and owner_id, and to remove the duplicated foreign keys.
2- Remove agent password for response data
3- Make the user agent or owner or both depending on the request.

listings-user-auth-endpoints

---

src/controllers/user.js
src/models/roles.js
src/models/user-roles.js
src/models/user.js
src/routes/index.js
src/routes/roles.js
src/routes/users.js
src/swagger.yml

- REV-38
- add get, update to user roles and get roles endpoints

REV-38-add get,update user roles and get roles endpoints

---

.eslintrc
src/controllers/listing.js
src/migrate.js
src/models/listing.js
src/routes/listings.js
src/server.js
src/swagger.yml

listing by search

---

.github/workflows/cicd.yml

Resolve local changes on package-lock.json by checkout before pulling
<Ticket>

Resolve the local changes on package-lock.json

---

src/controllers/user.js

fix update user info

---

src/controllers/user.js
src/routes/users.js

REV-89 find an agent cards duplication and filtration issues be

---

src/controllers/user.js

- fix agent list pagination issue

fix pagination issue

---

src/controllers/user.js

REV-111
- Improve location search for agents

REV-111-find-an-agent-filtration-and-search-issues

---

src/models/listing.js
src/seeders/20220209151409-add-listing-with-roles.js

https://optimumpartners.atlassian.net/browse/REV-109
add includes for listing search

REV-109 search listings backend

---

src/controllers/user.js

REV-112
- fix update user company issue

REV-112-profile-page-design-and-functionalities-issues

---

.eslintrc
src/controllers/listing.js
src/models/base-model.js
src/models/listing.js
src/swagger.yml

https://optimumpartners.atlassian.net/browse/REV-121
add my listing for the backend

REV-121 my listings

---

src/controllers/listing.js
src/controllers/user.js
src/migrations/20220213162737-modify-user-info-about-me-field.js
src/models/user-info.js
src/routes/listings.js
src/routes/users.js
src/swagger.yml

REV-124-agent-detailed-page-connect-to-backend

---

src/controllers/user.js

REV-112
- return id from company table

fix my profile bugs

---

src/controllers/listing.js
src/controllers/user.js
src/models/listing.js

fixed searsh by name

---

src/migrations/20220220093710-modify-company-table.js
src/models/company.js

<Ticket>
- fix company email issue (remove unique)

fix company email issue

---

src/seeders/20220220131253-modify-property-type-table-data.js

fix property type seed

---

src/controllers/listing.js
src/migrations/20220223113121-create-schedule-table.js
src/models/index.js
src/models/listing.js
src/models/schedule.js
src/routes/index.js
src/routes/schedule.js
src/swagger.yml

https://optimumpartners.atlassian.net/browse/REV-162
add schedule table

REV-162 update schedule

---

src/controllers/social-statistics.js
src/migrations/20220226123710-create-social-statistics-and-saved-users-listings-tables.js
src/models/index.js
src/models/listing.js
src/models/saved-users-listings.js
src/models/social-statistics.js
src/models/user.js
src/routes/index.js
src/routes/social-statistics.js
src/swagger.yml

REV-164
add social statistics and saved users listings tables

REV-164-create-listings-page-stats

---

src/controllers/review.js
src/migrations/20220222131015-create-reviews-ratings-and-review-ratings-tables.js
src/models/index.js
src/models/rating-criteria.js
src/models/review-ratings.js
src/models/reviews.js
src/models/user.js
src/routes/index.js
src/routes/rating-criteria.js
src/routes/reviews.js
src/seeders/20220222133140-add-user-ratings.js
src/swagger.yml

REV-150
- create review, rating criteria, review ratings tables

REV-150-agent-profile-rate-and-review

---

src/controllers/listing.js

REV-153
return tags with listing info

REV-153-create-listings-implement-special-tags

---

src/controllers/listing.js
src/controllers/schedule.js
src/migrations/20220228081455-create-schedule-visit-table.js
src/models/index.js
src/models/listing.js
src/models/schedule-visit.js
src/models/schedule.js
src/models/user.js
src/routes/schedule.js
src/swagger.yml

REV-146 my listings page 

---

src/controllers/social-statistics.js
src/models/listing-type.js
src/models/listing.js
src/models/property-type.js
src/routes/social-statistics.js
src/swagger.yml

REV-171, REV-172
- create get user saved users and listings endpoint

REV-171-create-saved-listings-tab

---

src/controllers/listing.js
src/models/listing.js

REV-252
- fix search listing bugs

REV-252-search-listing-data-are-not-rendering-correctly

---

src/controllers/review.js

[REV-208-rate-review-the-order-of-the-rates-selection-if-same-rates-are-selected-is-not-the-same-from-a-review-to-another-backend](https://optimumpartners.atlassian.net/browse/REV-208)
- order ratings from a-z

REV-208-rate-review-the-order-of-the-rates-selection-if-same-rates-are-selected-is-not-the-same-from-a-review-to-another-backend

---

src/controllers/listing.js

REV-246
- fix edit listing bug

REV-246-edit-listing-i-am-seller-and-seller-agent-buttons-features-updates

---

src/controllers/auth.js
src/controllers/user.js
src/migrations/20220309142533-add-active-column-to-users-table.js
src/models/user.js
src/routes/users.js
src/swagger.yml

[REV-285](https://optimumpartners.atlassian.net/browse/REV-285)
- add active column to users model

REV-285-step-01-invitation-feature

---

src/controllers/social-statistics.js

[<Ticket>](https://optimumpartners.atlassian.net/browse/REV-319)
- order saved listings and users

REV-319-saved-listing-the-most-recent-saved-listing-should-be-at-the-top-of-the-table

---

src/controllers/listing.js
src/models/listing.js

REV-314 update search price filters

---

src/migrations/20220313133534-create-transaction-tables.js
src/models/index.js
src/models/listing.js
src/models/processes.js
src/models/shared-columns.js
src/models/states.js
src/models/transaction-assignee.js
src/models/transaction-processes.js
src/models/transaction-workflow-steps.js
src/models/transactions-notes.js
src/models/transactions.js
src/models/user.js
src/seeders/20220313134950-add-transaction-workflows-steps-and-states-and-processes.js

[<Ticket>](https://optimumpartners.atlassian.net/browse/REV-345)
- Create transactions tables

REV-345-create-transaction-steps-tables-backend

---

src/controllers/auth.js
src/controllers/listing.js
src/controllers/transaction.js
src/models/listing.js
src/models/transaction-assignee.js
src/models/user.js
src/routes/index.js
src/routes/listings.js
src/routes/processes.js
src/routes/transactions.js

https://optimumpartners.atlassian.net/browse/REV-300
add transaction page

REV-300 create transactions page

---

src/controllers/transaction.js
src/routes/transactions.js

[<Ticket>](https://optimumpartners.atlassian.net/browse/REV-346)
- create transaction step 1 and step 2 endpoints

REV-346-connect-step-01-step-02

---

.gitignore
docker-compose.yml
package-lock.json
package.json
src/config/config.js
src/routes/index.js
src/routes/upload.js
src/swagger.yml

REV-390-uploading-assets
Add an endpoint for upload
Prep GCS bucket
Handle single file upload 
TODO:
Handle multiple files uploading
Fix swagger.io schema for single file uploading.

REV-390-uploading-assets

---

src/controllers/action-types.js
src/controllers/auth.js
src/controllers/user-action-types.js
src/migrations/20220308133109-create_action_types.js
src/models/action-types.js
src/models/user-action-types.js
src/models/user.js
src/routes/action-types.js
src/routes/index.js
src/routes/user-action-types.js
src/seeders/20220309100144-add-action-types.js
src/swagger.yml

<Ticket>
Implement points module:
1- Implement `action-type` endpoint
2- Implement `user-action-type` endpoint

Implement points module

---

src/controllers/listing.js

[<Ticket>](https://optimumpartners.atlassian.net/browse/REV-418)
- fix change ownerId and agentId when close deal

REV-418-transaction-for-the-recipient-when-the-deal-is-closed

---

package-lock.json
src/controllers/transaction.js
src/migrations/20220319145855-create-documents-and-documents-names-tables.js
src/models/documents-names.js
src/models/documents.js
src/models/index.js
src/models/states.js
src/models/transactions.js
src/models/user.js
src/routes/transactions.js
src/routes/upload.js
src/seeders/20220319150324-add-documents-names.js

[<Ticket>](https://optimumpartners.atlassian.net/browse/REV-398)
- add step 3 documents endpoints

REV-398-transaction-flow-step-3

---

.github/workflows/cicd.yml

Handle the docker-compose local changes
<Ticket>

Update CICD to handle local changes

---

src/controllers/transaction.js

[<Ticket>](https://optimumpartners.atlassian.net/browse/REV-412)
- include work step flow with transaction endpoints

REV-412-transaction-the-user-should-be-able-to-go-to-the-four-transaction-flow-steps-from-my-transactions-table

---

src/controllers/purchase-offer.js
src/controllers/user.js
src/migrations/20220317134950-create-purchase-offer.js
src/models/index.js
src/models/listing.js
src/models/purchase-offer.js
src/models/user.js
src/routes/index.js
src/routes/offer.js
src/routes/users.js

https://optimumpartners.atlassian.net/browse/REV-167
add purchase offer modal

REV-167-offers-table purchase counter offer forms

---

src/controllers/user.js

[<Ticket>](https://optimumpartners.atlassian.net/browse/REV-440)
- add email already exist in invited user endpoint

REV-440-step-01-updates

---

package-lock.json

hotFix: Fix package lock

---

docker-compose.yml

set node_env to prod

---

docker-compose.yml
package-lock.json
package.json
src/controllers/auth.js

remove bcrypt package

---

src/controllers/transaction.js
src/routes/transactions.js

https://optimumpartners.atlassian.net/browse/REV-457
- modify get documents endpoint

REV-457-transaction-uploads-are-the-same-once-uploaded-for-all-transactions

---

src/seeders/20220321100059-add-new-documents-names.js

https://optimumpartners.atlassian.net/browse/REV-463
- add new document names

REV-463-update-docs-title-for-nj-only

---

src/migrations/20220322094410-change-tranaction-duedate-type.js
src/models/transaction-processes.js

- https://optimumpartners.atlassian.net/browse/REV-444
- change due date column type

REV-444-step-02-dates-should-be-single-date

---

src/controllers/user.js

https://optimumpartners.atlassian.net/browse/REV-468
- modify update userInfo controller

REV-468-profile-page-profile-image-is-not-working

---

src/controllers/transaction.js
src/migrations/20220322115003-add-price-field-in-transactions.js
src/models/transactions.js

REV-399 add final selling price

---

src/controllers/listing.js
src/routes/listings.js
src/routes/upload.js

- https://optimumpartners.atlassian.net/browse/REV-456
- add upload multiple files endpoint and update listing images endpoint

REV-456-create-listing-edit-listing-upload-images

---

src/controllers/transaction.js

fix add transaction issue

---

src/models/listing.js

search query optimization

---

src/controllers/auth.js
src/routes/auth.js

add change-password endpoint
add to user data object isSocialRegistered key on login and signup 
add change-password and is-social-user endpoints

add change-password endpoint 

---

src/controllers/auth.js

https://optimumpartners.atlassian.net/browse/REV-119
fix regex for reset password

REV-119 fix reset password error message

---

docker-compose.yml

Added MailChimp env vars and their values
<Ticket>

Add MailChimp env vars and values
